### ISSUE TITLE
Question about tomorrow

### ISSUE THREAD

**Issue by julia-pearson-15** [julia-pearson/simon#3]
Hi there,

Is tomorrow's class focused on in-class code writing for projects? I'm wondering because I've been trying to get rid of a cold for a while now and was thinking it might be a good day to miss. I'm about done with my Simon Says but wouldn't want to miss class if we were learning any new concepts. Let me know!

**Comment by phlco** [comment]
Hi Julia, we're just scheduled for pairing sessions tomorrow. I say rest up.

Somethings you could work on tomorrow...

Keep your audio tags in the body, not the head. They could go right before the closing `body` tag.

In your JavaScript make sure you include spaces around your operators

``` js
// needs some space!
randomColor===0
// ahhhh I can breathe!
randomColor === 0
```

Another thing to do would be code organization. You could group all your audio assets, CSS, and JavaScript in sub folders. 

Get better!
